### ISSUE TITLE
Get SSH key from Christiaan so Zacck can be added to server

### ISSUE THREAD

**Issue by CIEspost** [zacck-zz/Menanawe#12]

**Comment by zacck-zz** [comment]
@CIEspost can we get this key so we can move the site to a cheaper host?

**Comment by CIEspost** [comment]
I asked him, waiting for a reply

**Comment by zacck-zz** [comment]
👍

**Comment by CIEspost** [comment]
@zacck christiaan is curently paying for menanawe;s hosting hey, its jsut the email adres that we are paying for right now

**Comment by zacck-zz** [comment]
@CIEspost yes true

**Comment by CIEspost** [comment]
ok, @zacck did you see the comment christiaan sent to you, see here hristiaan says "I can give you access to the repository of menanawe's site. When you push to master the site is automatically deployed live. Just send me your email address for bitbucket and I'll add you as a collaborator.. There is not much you can do with SSH access that can't be done either in the backend (menanawe.co.za./backend) or in the repository. If you need a database dump and a full file dump I can send you one."

**Comment by zacck-zz** [comment]
@CIEspost  I don't really need access the current site as you said you will be redisigning it to be responsive is there anything you need changed before then ?

**Comment by CIEspost** [comment]
@zacck no i am not changing it right now. please right a reply to christiaan then ill send it through to him as we are speaking via email at the moment

**Comment by zacck-zz** [comment]
@CIEspost  I haven't recieved an email from him

**Comment by CIEspost** [comment]
he send this in an email to me  "I can give you access to the repository of menanawe's site. When you push to master the site is automatically deployed live. Just send me your email address for bitbucket and I'll add you as a collaborator.. There is not much you can do with SSH access that can't be done either in the backend (menanawe.co.za./backend) or in the repository. If you need a database dump and a full file dump I can send you one."

**Comment by zacck-zz** [comment]
@CIEspost  tell him I say "Since we are not changing the site at the moment, I will not be needing the ssh key for now"
